# Generated by Django 5.1.7 on 2025-03-07 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('water_amount_ml', models.IntegerField(help_text='Optymalna ilość wody w ml')),
                ('watering_frequency_days', models.IntegerField(help_text='Optymalna częstotliwość podlewania (dni)')),
                ('sunlight', models.CharField(blank=True, choices=[('full_sun', 'Pełne słońce'), ('partial_shade', 'Półcień'), ('shade', 'Cień')], max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_temperature', models.IntegerField(blank=True, help_text='Temperatura °C', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('next_watering_date', models.DateField(blank=True, help_text='Data, kiedy roślina powinna być podlana', null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watered_at', models.DateTimeField(auto_now_add=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_history', to='myapp.userplant')),
            ],
        ),
    ]
