# Generated by Django 5.1.7 on 2025-03-14 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateringhistory',
            options={'ordering': ['-watered_at']},
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_amount_ml',
            field=models.PositiveIntegerField(help_text='Optymalna ilość wody w ml'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency_days',
            field=models.PositiveIntegerField(help_text='Optymalna częstotliwość podlewania (dni)'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='next_watering_date',
            field=models.DateField(blank=True, help_text='Data następnego podlewania', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userplant',
            unique_together={('user', 'plant')},
        ),
    ]
