# Generated by Django 5.1.7 on 2025-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250411_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('universal', 'Uniwersalna'), ('sandy', 'Piaszczysta'), ('peat', 'Torfowa'), ('clay', 'Gliniasta'), ('loamy', 'Próchnicza'), ('chalky', 'Wapienna')], help_text='Preferowany typ gleby', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_sun', 'Pełne słońce'), ('partial_shade', 'Półcień'), ('bright_indirect', 'Jasne rozproszone'), ('shade', 'Cień')], help_text='Wymagania dotyczące światła', max_length=50, null=True),
        ),
    ]
