# Generated by Django 5.2 on 2025-04-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_plant_soil_type_alter_plant_sunlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plant',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='Użytkownik, który zaproponował dodanie tej rośliny do bazy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Status zatwierdzenia rośliny w bazie globalnej', max_length=20),
        ),
    ]
